# label_settings.py

# === Defaultwaarden voor resetfunctie ===
DEFAULTS = {
    "LABEL_WIDTH": 85,
    "LABEL_HEIGHT": 25,
    "BARCODE_WIDTH_SCALE": 0.45,
    "BARCODE_HEIGHT_SCALE": 0.15,
    "BARCODE_Y": 18,
    "FONT_NAME": "Arial",
    "FONT_SIZE_ART": 6 ,   
    "FONT_SIZE_DESCRIPTION": 6,
    "DESCRIPTION_LEFT": 5,
    "FONT_SIZE_SUPPLIER": 6,
    "FONT_SIZE_INBOUND": 6,
    "FONT_SIZE_DATE": 6,
    "TEXT_Y_ART": 10,
    "TEXT_Y_DESCRIPTION": 10,
    "TEXT_Y_SUPPLIER": 7,
    "TEXT_Y_INBOUND": 4,
    "TEXT_Y_DATE": 1,
    "TEXT_X_LEFT": 10
}



# Grootte
LABEL_WIDTH = DEFAULTS["LABEL_WIDTH"]
LABEL_HEIGHT = DEFAULTS["LABEL_HEIGHT"]

# Barcode
BARCODE_WIDTH_SCALE = DEFAULTS["BARCODE_WIDTH_SCALE"]
BARCODE_HEIGHT_SCALE = DEFAULTS["BARCODE_HEIGHT_SCALE"]
BARCODE_Y = DEFAULTS["BARCODE_Y"]

# Fonts
FONT_NAME = DEFAULTS["FONT_NAME"]
FONT_SIZE_ART = DEFAULTS["FONT_SIZE_ART"]
FONT_SIZE_DESCRIPTION = DEFAULTS["FONT_SIZE_DESCRIPTION"]
FONT_SIZE_SUPPLIER = DEFAULTS["FONT_SIZE_SUPPLIER"]
FONT_SIZE_INBOUND = DEFAULTS["FONT_SIZE_INBOUND"]
FONT_SIZE_DATE = DEFAULTS["FONT_SIZE_DATE"]

# Tekstposities
TEXT_Y_ART = DEFAULTS["TEXT_Y_ART"]
TEXT_Y_DESCRIPTION = DEFAULTS["TEXT_Y_DESCRIPTION"]
TEXT_Y_SUPPLIER = DEFAULTS["TEXT_Y_SUPPLIER"]
TEXT_Y_INBOUND = DEFAULTS["TEXT_Y_INBOUND"]
TEXT_Y_DATE = DEFAULTS["TEXT_Y_DATE"]

TEXT_X_LEFT = DEFAULTS["TEXT_X_LEFT"]
